NCEPLIBS-bufr: ftbvs.F90 File Reference
ftbvs.F90 File Reference
Convert between flag table bit settings and numerical data values.
Functions/Subroutines
recursive real *8 function pkftbv (nbits, ibit)
Compute the numerical value equivalent to the setting of bit #(ibit) within a flag table of nbits bits.
recursive subroutine upftbv (lunit, nemo, val, mxib, ibit, nib)
Given a Table B mnemonic with flag table units and a corresponding numerical data value, this subroutine determines the bit settings equivalent to that numerical value.
Detailed Description
Convert between flag table bit settings and numerical data values.
Author
J. Ator
Date
2005-11-29
Definition in file ftbvs.F90.
Function/Subroutine Documentation
pkftbv()
recursive real*8 function pkftbv (integer, intent(in) nbits, integer, intent(in) ibit)
Compute the numerical value equivalent to the setting of bit #(ibit) within a flag table of nbits bits.
If the computation fails for any reason, then the function returns the current placeholder value for "missing" data.
Parameters
nbits - Total number of bits in flag table
ibit - Number of bit to be set
Returns
pkftbv - real*8: Value equivalent to the setting of bit #(ibit) within a flag table of nbits bits
Remarks
This function is the logical inverse of subroutine upftbv().
According to the WMO standard, bits within a bit field are numbered from left to right, so bit #1 is always the high-order (i.e. most significant) bit in any bit field.
Author
J. Ator
Date
2005-11-29
Definition at line 21 of file ftbvs.F90.
References x84().
upftbv()
recursive subroutine upftbv (integer, intent(in) lunit, character*(*), intent(in) nemo, real*8, intent(in) val, integer, intent(in) mxib, integer, dimension(*), intent(out) ibit, integer, dimension(*), intent(out) nib)
Given a Table B mnemonic with flag table units and a corresponding numerical data value, this subroutine determines the bit settings equivalent to that numerical value.
This subroutine is the logical inverse of function pkftbv().
According to the WMO standard, bits within a bit field are numbered from left to right, so bit #1 is always the high-order i.e. most significant) bit in any bit field.
Parameters
lunit - Fortran logical unit number for BUFR file
nemo - Table B mnemonic with flag table units
val - Value corresponding to nemo
mxib - Dimensioned size (in integers) of ibit in the calling program; used by the subroutine to ensure that it doesn't overflow the ibit array
ibit - Bit numbers which were set to "On" (i.e. set to "1") in val
nib - Number of bit numbers returned in ibit
Author
J. Ator
Date
2005-11-29
Definition at line 69 of file ftbvs.F90.
References bort(), nemtab(), status(), strnum(), moda_tababd::tabb, x48(), and x84().
Referenced by ufbdmp(), and ufdump().