NCEPLIBS-bufr: jumplink.F90 File Reference
jumplink.F90 File Reference
Build the internal jump/link table.
Functions/Subroutines
subroutine chekstab (lun)
Check that an internal BUFR table representation is self-consistent and fully defined.
subroutine drstpl (inod, lun, inv1, inv2, invn)
Search for a specified mnemonic within unexpanded sequences of the internal jump/link table.
integer function icmpdx (lud, lun)
Check whether the full set of associated DX BUFR Table information is identical between two Fortran logical units.
subroutine inctab (atag, atyp, node)
Get the next available positional index for writing into the internal jump/link table in module moda_tables, and also use that index to store atag and atyp within, respectively, the internal jump/link table arrays tag(*) and typ(*).
integer function ishrdx (lud, lun)
Check whether the same DX BUFR Table is being shared between two Fortran logical units.
integer function lstjpb (node, lun, jbtyp)
Search backwards, beginning from a given node within the jump/link table, until finding the most recent node of type jbtyp.
subroutine makestab
Build the entire internal jump/link table within module moda_tables, using all of the internal BUFR table array information from module moda_tababd for all of the file IDs that are currently defined to the library in module moda_stbfr.
recursive subroutine nemspecs (lunit, nemo, nnemo, nscl, nref, nbts, iret)
Get the scale factor, reference value and bit width associated with a specified occurrence of a Table B mnemonic.
subroutine tabent (lun, nemo, tab, itab, irep, iknt, jum0)
Build and store an entry for a Table B or Table D mnemonic within the internal jump/link table.
subroutine tabsub (lun, nemo)
Build and store the entire jump/link tree (including recursively resolving all "child" mnemonics) for a Table A mnemonic within the internal jump/link table.
Detailed Description
Build the internal jump/link table.
Author
J. Woollen
Date
1994-01-06
Definition in file jumplink.F90.
Function/Subroutine Documentation
chekstab()
subroutine chekstab (integer, intent(in) lun)
Check that an internal BUFR table representation is self-consistent and fully defined.
If any errors are found, then make an appropriate call to NCEPLIBS-bufr subroutine bort().
Parameters
lun - File ID
Author
Woollen
Date
1994-01-06
Definition at line 279 of file jumplink.F90.
References bort(), moda_nmikrp::irp, moda_nmikrp::krp, moda_nmikrp::nem, nemtab(), nemtbb(), nemtbd(), moda_tababd::ntba, moda_tababd::ntbb, moda_tababd::ntbd, and moda_tababd::taba.
Referenced by makestab().
drstpl()
subroutine drstpl (integer, intent(in) inod, integer, intent(in) lun, integer, intent(in) inv1, integer, intent(inout) inv2, integer, intent(out) invn)
Search for a specified mnemonic within unexpanded sequences of the internal jump/link table.
This subroutine is called internally by subroutine ufbrw() whenever it can't find a mnemonic it wants to write within the current subset buffer. It looks for the mnemonic within any unexpanded "DRS" (stack) or "DRB" (1-bit delayed replication) sequences inside of the portion of the subset buffer bounded by the indices inv1 and inv2. If found, it expands the applicable "DRS" or "DRB" sequence to the point where the mnemonic in question now appears in the subset buffer, and in doing so it will also return a new value for inv2.
Parameters
inod - Jump/link table index of mnemonic to look for
lun - File ID
inv1 - Starting index of the portion of the subset buffer currently being processed by ufbrw()
inv2 - Ending index
On input, ending index of the portion of the subset buffer currently being processed by ufbrw()
On output, if invn = 0 then inv2 is unchanged from its input value. Otherwise, it contains the redefined ending index of the portion of the subset buffer currently being processed by ufbrw(), since expanding a delayed replication sequence will have necessarily increased the size of this buffer.
invn - Location index of inod within subset buffer
0 = Not found
Author
Woollen
Date
1994-01-06
Definition at line 900 of file jumplink.F90.
References moda_tables::jmpb, newwin(), moda_tables::typ, and usrtpl().
Referenced by ufbrw().
icmpdx()
integer function icmpdx (integer, intent(in) lud, integer, intent(in) lun)
Check whether the full set of associated DX BUFR Table information is identical between two Fortran logical units.
Note that two different logical units can have identical DX BUFR Table information associated with them even if they aren't actually sharing the same DX BUFR table.
Parameters
lud - File ID for first BUFR file
lun - File ID for second BUFR file
Returns
icmpdx - Flag indicating whether the BUFR file associated with lud and the BUFR file associated with lun have the same DX BUFR table information
0 = No
1 = Yes
Author
J. Ator
Date
2009-06-18
Definition at line 834 of file jumplink.F90.
References moda_tababd::idna, moda_tababd::idnb, moda_tababd::idnd, ishrdx(), moda_tababd::ntba, moda_tababd::ntbb, moda_tababd::ntbd, moda_tababd::taba, moda_tababd::tabb, and moda_tababd::tabd.
Referenced by iok2cpy().
inctab()
subroutine inctab (character*(*), intent(in) atag, character*(*), intent(in) atyp, integer, intent(out) node)
Get the next available positional index for writing into the internal jump/link table in module moda_tables, and also use that index to store atag and atyp within, respectively, the internal jump/link table arrays tag(*) and typ(*).
If there is no more room for additional entries within the internal jump/link table, then an appropriate call is made to subroutine bort().
Parameters
atag - Mnemonic name
atyp - Mnemonic type
node - Next available positional index for writing into the internal jump/link table
Author
Woollen
Date
1994-01-06
Definition at line 698 of file jumplink.F90.
References bort(), moda_tables::ntab, moda_tables::tag, and moda_tables::typ.
Referenced by tabent(), and tabsub().
ishrdx()
integer function ishrdx (integer, intent(in) lud, integer, intent(in) lun)
Check whether the same DX BUFR Table is being shared between two Fortran logical units.
Parameters
lud - File ID for first BUFR file
lun - File ID for second BUFR file
Returns
ishrdx - Flag indicating whether the same DX BUFR table is being shared between the BUFR file associated with lud and the BUFR file associated with lun
0 = No
1 = Yes
Author
J. Ator
Date
2009-06-18
Definition at line 789 of file jumplink.F90.
References moda_tababd::mtab, and moda_tababd::ntba.
Referenced by icmpdx().
lstjpb()
integer function lstjpb (integer, intent(in) node, integer, intent(in) lun, character*(*), intent(in) jbtyp)
Search backwards, beginning from a given node within the jump/link table, until finding the most recent node of type jbtyp.
The internal jmpb array is used to jump backwards within the jump/link table, and the function returns the table index of the found node. If the input node itself is of type jbtyp, then the function simply returns the index of that same node.
Note
See module moda_tables for an explanation of the various node types present within an internal jump/link table.
Parameters
node - Jump/link table index of entry to begin searching backwards from
lun - File ID
jbtyp - Type of node for which to search
Returns
- Index of first node of type jbtyp found by jumping backwards from input node
0 no such node found
Author
Woollen
Date
1994-01-06
Definition at line 743 of file jumplink.F90.
References bort(), moda_msgcwd::inode, moda_tables::isc, moda_tables::jmpb, and moda_tables::typ.
Referenced by getwin(), igetrfel(), nevn(), newwin(), nxtwin(), parusr(), and trybump().
makestab()
subroutine makestab
Build the entire internal jump/link table within module moda_tables, using all of the internal BUFR table array information from module moda_tababd for all of the file IDs that are currently defined to the library in module moda_stbfr.
The entire jump/link table will always be completely reconstructed from scratch, even if some of the information within the internal BUFR table arrays already existed there at the time of the previous call to this subroutine, because there may have been other events that have taken place since the previous call to this subroutine and which haven't yet been reflected within the internal jump/link table. For example, a file ID may have recently been unlinked from the library via an internal call to subroutine closbf(), or the DX BUFR tables associated with a file ID may have changed.
Author
J. Woollen
Date
1994-01-06
Definition at line 22 of file jumplink.F90.
References bort(), chekstab(), closmg(), cpbfdx(), errwrt(), moda_tables::ibt, moda_usrint::inv, moda_stbfr::iolun, moda_stbfr::iomsg, moda_tables::irf, moda_tables::isc, moda_tables::iseq, moda_tables::itp, moda_tables::jmpb, moda_tables::jseq, moda_tables::jump, moda_tables::knt, moda_tables::knti, moda_tables::link, moda_lushr::lus, moda_tababd::mtab, moda_nrv203::nnrv, moda_tables::ntab, moda_bitmaps::ntamc, moda_tababd::ntba, moda_usrint::nval, strcln(), moda_tababd::taba, tabsub(), moda_tables::tag, moda_tables::typ, moda_tables::vali, wrdxtb(), and moda_xtab::xtab.
Referenced by rdbfdx(), rdmemm(), rdusdx(), readdx(), readerme(), and reads3().
nemspecs()
recursive subroutine nemspecs (integer, intent(in) lunit, character*(*), intent(in) nemo, integer, intent(in) nnemo, integer, intent(out) nscl, integer, intent(out) nref, integer, intent(out) nbts, integer, intent(out) iret)
Get the scale factor, reference value and bit width associated with a specified occurrence of a Table B mnemonic.
Given a Table B mnemonic defined within a data subset, this subroutine returns the scale factor, reference value and bit width of a specified occurrence of that mnemonic within the overall data subset definition, counting from the beginning of the subset.
The values returned include the application of any Table C operators (e.g. 2-01-YYY, 2-02-YYY, 2-03-YYY, 2-07-YYY, 2-08-YYY) which may be in effect for the specified occurrence of the mnemonic.
Parameters
lunit - Fortran logical unit number for BUFR file
nemo - character*(*): Table B mnemonic
nnemo - Ordinal occurrence of nemo for which information is to be returned, counting from the beginning of the overall subset definition
nscl - Scale factor in effect for (nnemo)th occurrence of nemo
nref - Reference value in effect for (nnemo)th occurrence of nemo
nbts - Bit width in effect for (nnemo)th occurrence of nemo
iret - Return code
0 = normal return
-1 = nemo could not be found, or some other error occurred
A data subset must already be in scope within the NCEPLIBS-bufr internal arrays for lunit, either via a previous call to one of the subset-reading subroutines (when reading BUFR data subsets) or via a previous call to one of the message-writing subroutines (when writing BUFR data subsets).
Author
J. Ator
Date
2014-10-02
Definition at line 964 of file jumplink.F90.
References fstag(), moda_tables::ibt, moda_nrv203::ienrv, moda_msgcwd::inode, moda_nrv203::inodnrv, moda_usrint::inv, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_nrv203::nnrv, moda_nrv203::nrv, status(), strsuc(), moda_nrv203::tagnrv, moda_tables::typ, x48(), and x84().
Referenced by bufr_c2f_interface::nemspecs_c().
tabent()
subroutine tabent (integer, intent(in) lun, character*8, intent(in) nemo, character, intent(in) tab, integer, intent(in) itab, integer, intent(in) irep, integer, intent(in) iknt, integer, intent(in) jum0)
Build and store an entry for a Table B or Table D mnemonic within the internal jump/link table.
Parameters
lun - File ID
nemo - Table B or D mnemonic to store in jump/link table
tab - Internal BUFR table array ('B' or 'D') in which nemo is defined
itab - Positional index of nemo within TAB
irep - Positional index within common /reptab/ arrays, for use when nemo is replicated:
0, if nemo is not replicated
iknt - Number of replications, for use when nemo is replicated using F=1 regular (i.e., non-delayed) replication:
0, if nemo is not replicated using F=1 regular (i.e., non-delayed) replication
jum0 - Index value to be stored for nemo within internal jump/link table array jmpb(*)
Author
Woollen
Date
1994-01-06
Definition at line 585 of file jumplink.F90.
References bort(), moda_tables::ibt, moda_nrv203::ibtnrv, inctab(), moda_nrv203::inodnrv, moda_nrv203::ipfnrv, moda_tables::irf, moda_tables::isc, moda_nrv203::isnrv, moda_tables::jmpb, moda_tables::jump, moda_tables::link, nemtbb(), moda_nrv203::nnrv, and moda_nrv203::tagnrv.
Referenced by tabsub().
tabsub()
subroutine tabsub (integer, intent(in) lun, character*8, intent(in) nemo)
Build and store the entire jump/link tree (including recursively resolving all "child" mnemonics) for a Table A mnemonic within the internal jump/link table.
Parameters
lun - File ID
nemo - Table A mnemonic
Author
Woollen
Date
1994-01-06
Definition at line 333 of file jumplink.F90.
References bort(), moda_bitmaps::ctco, moda_tables::ibt, moda_nrv203::ibtnrv, moda_nrv203::ienrv, inctab(), moda_bitmaps::inodtamc, moda_bitmaps::inodtco, moda_nrv203::ipfnrv, moda_tables::irf, moda_nmikrp::irp, moda_tables::isc, moda_tables::jmpb, moda_tables::jump, moda_nmikrp::krp, moda_tables::link, moda_nmikrp::nem, nemtab(), nemtbd(), moda_nrv203::nnrv, moda_tables::ntab, moda_bitmaps::ntamc, moda_bitmaps::ntco, and tabent().
Referenced by makestab().