NCEPLIBS-bufr: mesgbf.f File Reference
mesgbf.f File Reference
Get information about a BUFR message.
Functions/Subroutines
recursive subroutine mesgbf (LUNIT, MESGTYP)
Read through a BUFR file (starting from the beginning of the file) and return the message type (from Section 1) of the first message encountered which does not contain DX BUFR table information.
Detailed Description
Get information about a BUFR message.
Author
J. Woollen
Date
1994-01-06
Definition in file mesgbf.f.
Function/Subroutine Documentation
mesgbf()
recursive subroutine mesgbf (LUNIT, MESGTYP)
Read through a BUFR file (starting from the beginning of the file) and return the message type (from Section 1) of the first message encountered which does not contain DX BUFR table information.
The BUFR file should not have already been opened via a call to subroutine openbf(); however, it should already be associated with Fortran logical unit number LUNIT.
This subroutine is similar to subroutine mesgbc(), except that this subroutine will only skip past DX BUFR table messages at the beginning of a file, whereas mesgbc() will also skip past any "dummy" messages containing the dump center time or dump initiation time within NCEP dump files. Furthermore, mesgbc() also returns a message compression indicator, and it also has an option to operate on a BUFR message that has already been read into the internal arrays.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file
[out] MESGTYP - integer: Message type
-1 = error reading the BUFR file, or no messages were read from the file
11 = BUFR file only contained DX BUFR table messages
Author
J. Woollen
Date
1994-01-06
Definition at line 32 of file mesgbf.f.
References closbf(), idxmsg(), iupbs01(), moda_mgwa::mgwa, openbf(), rdmsgw(), x48(), and x84().