NCEPLIBS-bufr: ufbovr.f File Reference
ufbovr.f File Reference
Overwrite one or more data values within a data subset.
Functions/Subroutines
recursive subroutine ufbovr (LUNIT, USR, I1, I2, IRET, STR)
Overwrite specified values which exist in current internal BUFR subset arrays in a file open for output.
Detailed Description
Overwrite one or more data values within a data subset.
Author
Woollen
Date
1994-01-06
Definition in file ufbovr.f.
Function/Subroutine Documentation
ufbovr()
recursive subroutine ufbovr (LUNIT, real*8, dimension(i1,i2) USR, I1, I2, IRET, character*(*) STR)
Overwrite specified values which exist in current internal BUFR subset arrays in a file open for output.
The data values correspond to mnemonics which are part of a delayed-replication sequence, or for which there is no replication at all. Either subroutine openmg() or openmb() must have been previously called to open and initialize a BUFR message within memory for this lunit. In addition, subroutine writsb() or invmrg() must have been called to store data in the internal output subset arrays.
Parameters
[in] LUNIT - integer: Fortran logical unit number for BUFR file.
[in] USR - real*8(*,*): data values
[in] I1 - integer: First dimension of USR as allocated within the calling program.
[in] I2 - integer: Number of replications of STR that are to be written into the data subset.
[out] IRET - integer: Number of replications of STR that were written into the data subset.
[in] STR - character*(*): string of blank-separated Table B mnemonics in one-to-one correspondence with first dimension of USR.
Author
Woollen
Date
1994-01-06
Definition at line 28 of file ufbovr.f.
References bort(), bort2(), errwrt(), moda_msgcwd::inode, moda_usrint::inv, status(), string(), trybump(), x48(), and x84().