NCEPLIBS-bufr: ufbqcp.f File Reference
ufbqcp.f File Reference
Get the Table D mnemonic associated with an event program code from an NCEP prepbufr file.
Functions/Subroutines
recursive subroutine ufbqcp (LUNIT, IQCP, NEMO)
Given an event program code, which is equivalent to the Y value of a category 63 Table D descriptor from an NCEP prepbufr file, return the corresponding mnemonic.
Detailed Description
Get the Table D mnemonic associated with an event program code from an NCEP prepbufr file.
Author
J. Woollen
Date
1994-01-06
Definition in file ufbqcp.f.
Function/Subroutine Documentation
ufbqcp()
recursive subroutine ufbqcp (LUNIT, IQCP, character*(*) NEMO)
Given an event program code, which is equivalent to the Y value of a category 63 Table D descriptor from an NCEP prepbufr file, return the corresponding mnemonic.
Logical unit LUNIT should have already been opened via a previous call to subroutine openbf().
This subroutine is the logical inverse of subroutine ufbqcd().
Parameters
[in] LUNIT - integer: Fortran logical unit number for NCEP prepbufr file.
[in] IQCP - integer: Y value of a category 63 (i.e. X=63) Table D descriptor.
[out] NEMO - character*(*): Mnemonic associated with IQCP.
Author
J. Woollen
Date
1994-01-06
Definition at line 23 of file ufbqcp.f.
References bort(), ifxy(), numtab(), status(), and x84().