NCEPLIBS-bufr: x4884.F90 File Reference
x4884.F90 File Reference
Convert between 4-byte integers and 8-byte integers.
Functions/Subroutines
subroutine setim8b (int8b)
Specify whether all integer arguments to NCEPLIBS-bufr subprograms from Fortran will use 8-byte integers.
subroutine x48 (iin4, iout8, nval)
Encode one or more 4-byte integer values as 8-byte integer values.
subroutine x84 (iin8, iout4, nval)
Encode one or more 8-byte integer values as 4-byte integer values.
Detailed Description
Convert between 4-byte integers and 8-byte integers.
Author
J. Woollen
Date
2022-10-12
Definition in file x4884.F90.
Function/Subroutine Documentation
setim8b()
subroutine setim8b (logical, intent(in) int8b)
Specify whether all integer arguments to NCEPLIBS-bufr subprograms from Fortran will use 8-byte integers.
The default value is .false., meaning that if this subroutine is never called, then the NCEPLIBS-bufr will expect that all future calls from the application program will use 4-byte integer arguments. Otherwise, the specification in any call to this subroutine remains in effect unless and until it is overridden by a subsequent future call to this same subroutine.
Parameters
int8b - .true. iff 8-byte integers will be used for all integer arguments passed to and from all future calls to NCEPLIBS-bufr subprograms from within the application program
Author
J. Ator
Date
2022-09-01
Definition at line 106 of file x4884.F90.
x48()
subroutine x48 (integer, dimension(*), intent(in) iin4, integer, dimension(*), intent(out) iout8, integer, intent(in) nval)
Encode one or more 4-byte integer values as 8-byte integer values.
Note
iin4 and iout8 may be the same array, as long as the underlying memory contains sufficient space for the equivalent number of 8-byte integer values.
Parameters
iin4 - Value(s) encoded as 4-byte integers
iout8 - Value(s) from iin4 now re-encoded as 8-byte integers
nval - Number of values in iin4 to be re-encoded
Author
J. Woollen
Date
2022-10-12
Definition at line 17 of file x4884.F90.
References mvb().
Referenced by copysb(), datebf(), dumpbf(), fortran_close(), fortran_open(), getabdb(), getcfmng(), getlens(), gets1loc(), gettagpr(), gettagre(), igetdate(), ireadmg(), ireadmm(), ireadns(), mesgbc(), mesgbf(), nemdefs(), nemspecs(), openbt(), rdmemm(), rdmems(), readerme(), readmg(), readmm(), readns(), readsb(), rtrcpt(), rtrcptb(), setvalnb(), status(), strnum(), ufbcnt(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbinx(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbovr(), ufbpos(), ufbqcd(), ufbrep(), ufbrms(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), upds3(), upftbv(), and writsa().
x84()
subroutine x84 (integer, dimension(*), intent(in) iin8, integer, dimension(*), intent(out) iout4, integer, intent(in) nval)
Encode one or more 8-byte integer values as 4-byte integer values.
Note
iin8 and iout4 may be the same array.
Parameters
iin8 - Value(s) encoded as 8-byte integers
iout4 - Value(s) from iin8 now re-encoded as 4-byte integers
nval - Number of values in iin8 to be re-encoded
Author
J. Woollen
Date
2022-10-12
Definition at line 64 of file x4884.F90.
References mvb().
Referenced by atrcpt(), closbf(), closmg(), cnved4(), copybf(), copymg(), copysb(), cpymem(), datebf(), datelen(), drfini(), dumpbf(), dxdump(), fortran_close(), fortran_open(), getabdb(), getcfmng(), getlens(), gets1loc(), gettagpr(), gettagre(), getvalnb(), hold4wlc(), i4dy(), icbfms(), icopysb(), ifbget(), igetsc(), invmrg(), ipkm(), ireadmg(), ireadmm(), ireadns(), ireadsb(), isetprm(), iupb(), iupm(), iupvs01(), lcmgdf(), maxout(), mesgbc(), mesgbf(), minimg(), mtinfo(), nemdefs(), nemspecs(), nmsub(), openbf(), openbt(), openmb(), openmg(), pkbs1(), pkftbv(), pkvs01(), rdmemm(), rdmems(), rdmgsb(), readerme(), readlc(), readmg(), readmm(), readns(), readsb(), rtrcpt(), setblock(), setvalnb(), status(), stndrd(), strcpt(), ufbcnt(), ufbcpy(), ufbcup(), ufbdmp(), ufbevn(), ufbget(), ufbin3(), ufbint(), ufbinx(), ufbmem(), ufbmex(), ufbmms(), ufbmns(), ufbovr(), ufbpos(), ufbqcd(), ufbqcp(), ufbrep(), ufbrms(), ufbseq(), ufbstp(), ufbtab(), ufbtam(), ufdump(), upds3(), upftbv(), wrdxtb(), writcp(), writlc(), writsa(), and writsb().